#!/usr/bin/env python

import argparse
from robobo.robobo_topics_services import ROBOBO_TOPICS_SERVICES

def start_robobo_services_server():
	"""Create a Robobo Services Server object and run it"""
	parser = argparse.ArgumentParser(description="This script starts the Robobo Services Server")
	parser.add_argument("-n", "--robobo_name", help="The name of the robot")
	args, _ = parser.parse_known_args()
	kwargs = vars(args)
	robobo_name = kwargs.pop("robobo_name", None)
	robobo_services_server = ROBOBO_TOPICS_SERVICES(robobo_name)
	robobo_services_server.run()
if __name__ == "__main__":
	start_robobo_services_server()
