#!/usr/bin/env python

import argparse
from robobo.robobo_irs import ROBOBO_IRS

def start_robobo_irs():
	"""Create a Robobo IRS object and run it"""
	parser = argparse.ArgumentParser(description="This script starts the Robobo IRS")
	parser.add_argument("-n", "--robobo_name", help="The name of the robot")
	args, _ = parser.parse_known_args()
	kwargs = vars(args)
	robobo_name = kwargs.pop("robobo_name", None)
	robobo_irs = ROBOBO_IRS(robobo_name)
	robobo_irs.run()
if __name__ == "__main__":
	start_robobo_irs()
